# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20160720_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAlumno', models.CharField(max_length=12)),
                ('idMateria', models.CharField(max_length=5)),
                ('verificador', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
